version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.0

    steps:
      # Checkout the code as the first step.
      - checkout

      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # Then start the emulator and run the Instrumentation tests!
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
workflows:
  sample:
    jobs:
      - build-and-test
