package com.example.messagingapp.network.services

import com.example.messagingapp.model.conversation_model.FakeMessagesData
import io.reactivex.rxjava3.core.Flowable
import retrofit2.http.GET
import retrofit2.http.Query

interface MessagesApiService {

    /**
     * This endpoint has been built on the API contract available here: https://fakerapi.it/en
     *
     * All the queries are String types because Faker Api will generate date with the correct type for us.
     * The typing must be exact to the specs on the website in our User DTO
     *
     * @param randomDataLang: Configuration param to tell the API to generate random data in a specific language
     * @param responseLength: Number of elements generated by the API
     *
     * @param isMyMessage: Random boolean to know if a message is sent by me or by the person i am messaging
     * @param message: Content of the text message
     */
    @GET("custom")
    fun getRandomConversation(
        @Query("_locale") randomDataLang: String,
        @Query("_quantity") responseLength: Int,
        @Query("isMyMessage") isMyMessage: String,
        @Query("message") message: String
    ): Flowable<FakeMessagesData>
}