package com.example.messagingapp.network.services

import com.example.messagingapp.model.user_model.FakeUserDto
import io.reactivex.rxjava3.core.Flowable
import retrofit2.http.GET
import retrofit2.http.Query

interface UserApiService {

    /**
     * This endpoint has been built on the API contract available here: https://fakerapi.it/en
     *
     * All the queries are String types because Faker Api will generate date with the correct type for us.
     * The typing must be exact to the specs on the website in our User DTO
     *
     * @param randomDataLang: Configuration param to tell the API to generate random data in a specific language
     * @param responseLength: Number of elements generated by the API
     *
     * @param userName: Random user name
     * @param userLastName: Random user last name
     * @param userLastSeenDate: Random date object representing the last time user has been seen.
     * @param status: User status random text.
     * @param phoneNumber: User random phone number
     * @param isPremium: Random boolean to know if a user has subscribed to premium account
     */
    @GET("custom")
    fun getOneRandomUserData(
        @Query("_locale") randomDataLang: String,
        @Query("_quantity") responseLength: Int,
        @Query("id") id: String,
        @Query("profilePicture") profilePicture: String,
        @Query("name") userName: String,
        @Query("lastName") userLastName: String,
        @Query("lastSeenDate") userLastSeenDate: String,
        @Query("statusDescription") status: String,
        @Query("phoneNumber") phoneNumber: String,
        @Query("isPremium") isPremium: String
    ): Flowable<FakeUserDto>
}